wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [ 32, 32, 32, 32, 90 ]
    rows: [ 10, 10, 10, 4, 4, 90 ]
  refreshInterval: 1
  mods:
    digitalclock:
      color: orange
      enabled: true
      font: bigfont
      hourFormat: 24
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 1m
      title: "big clock"
      type: "digitalclock"
    resourceusage:
      cpuCombined: false
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 10s
      showCPU: true
      showMem: true
      showSwp: true
    duf:
      type: "cmdrunner"
      args: [ "-only", "local", "-output", "mountpoint,usage" ]
      cmd: "duf"
      enabled: true
      position:
        top: 0
        left: 3
        height: 1
        width: 1
      refreshInterval: 1m
    feedreader:
      enabled: true
      feeds:
        - https://www.cert.ssi.gouv.fr/feed/
      feedLimit: 10
      position:
        top: 1
        left: 1
        width: 3
        height: 1
      refreshInterval: 1h
    prettyweather:
      enabled: true
      city: "nice"
      position:
        top: 2
        left: 3
        height: 1
        width: 1
      refreshInterval: 5m
      unit: "m"
      view: 0
      language: "fr"
    ipinfo:
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 2
        left: 1
        height: 1
        width: 1
      refreshInterval: 1h
    power:
      enabled: true
      position:
        top: 2
        left: 2
        height: 1
        width: 1
      refreshInterval: 10m
      title: "⚡️"
    zou:
      type: "cmdrunner"
      cmd: "zou"
      args: []
      enabled: true
      position:
        top: 3
        left: 1
        height: 1
        width: 1
      refreshInterval: 1m
    correos:
      title: "correos"
      type: "cmdrunner"
      cmd: "correos"
      args: [ "RF070419721ES" ]
      enabled: true
      position:
        top: 3
        left: 2
        height: 1
        width: 2
      refreshInterval: 1m
    gita:
      type: "cmdrunner"
      args: [ "ll" ]
      cmd: "/usr/bin/gita"
      enabled: true
      position:
        top: 4
        left: 1
        height: 2
        width: 3
      refreshInterval: 1m
