disable = ["nix", "gem", "node"]
no_retry = true
cleanup = true

[commands]
#"Gem update" = "sudo gem cleanup;sudo gem update;sudo gem cleanup"
"nix-collect-garbage" = "nix-collect-garbage"
"APT cleanup" = "sudo apt autoremove -y;sudo apt autoclean -y"
#"ASDF reshim rust" = "asdf reshim rust"
"Gita Pull" = "gita pull"
"Needrestart?" = "sudo needrestart"
